version: '2'
services:
  # ====================================================================================================================
  bitcoind:
    image: ruimarinho/bitcoin-core:0.15.1
    volumes:
      - ./target/docker/bitcoind:/home/bitcoin/.bitcoin
    ports:
      - 8332:8332
    command:
      -server=1
      -rest=1
      -rpcuser=bitcoinrpc
      -rpcpassword=JRkDy3tgCYdmCEqY1VdfdfhTswiRva
      -txindex=1
      -rpcallowip=0.0.0.0/0
      -rpcallowip=::/0
  # ====================================================================================================================
  neo4j:
    image: neo4j:3.3.3
    volumes:
      - ./target/docker/neo4j:/var/lib/neo4j/data
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/neo4j123
  # ====================================================================================================================
  blockchain2graph:
    image: straumat/blockchain2graph:2.1-SNAPSHOT
    ports:
      - 8080:8080
    links:
      - bitcoind
      - neo4j
    environment:
      - BLOCKCHAIN2GRAPH_ADDRESS=localhost
      - BITCOIND_HOSTNAME=bitcoind # Public server : 5.196.65.205
      - BITCOIND_USERNAME=bitcoinrpc
      - BITCOIND_PASSWORD=JRkDy3tgCYdmCEqY1VdfdfhTswiRva
      - SPRING_DATA_NEO4J_URI=bolt://neo4j:neo4j123@neo4j:7687