version: '2'
services:
  bitcoin:
    image:  kylemanna/bitcoind
    volumes:
      - ./data/bitcoin:/bitcoin
    ports:
      - 8332:8332
    environment:
      - DISABLEWALLET=1
      - PRINTTOCONSOLE=1
      - RPCUSER=bitcoinrpc
      - RPCPASSWORD=JRkDy3tgCYdmCEqY1VdfdfhTswiRva
  neo4j:
    image: neo4j:3.1.1
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
      - ./data/neo4j/data:/data
      - ./data/neo4j/logs:/logs
  app:
    image: oakinvest/blockchain2graph
    ports:
      - 8080:8080
    links:
      - bitcoin
      - neo4j
    environment:
      - BLOCKCHAIN2GRAPH_ADDRESS=localhost
      - BITCOIND_HOSTNAME=bitcoin
      - BITCOIND_USERNAME=bitcoinrpc
      - BITCOIND_PASSWORD=JRkDy3tgCYdmCEqY1VdfdfhTswiRva
      - SPRING_DATA_NEO4J_URI=bolt://neo4j:neo4j123@neo4j:7687